### ISSUE TITLE
Crash app when use function getLightDataPoint()

### ISSUE THREAD

**Issue by ffantasy94** [tuya/tuya-lighting-ios-sdk#1]
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString substringWithRange:]: Range {12, 2} out of bounds; string length 12'
*** First throw call stack:
(0x181ca504c 0x19a319f54 0x181dae530 0x181c5a544 0x1033a616c 0x1033a5230 0x103152030 0x1031527b0 0x106682368 0x1065f1110 0x106688720 0x106688998 0x1066c4c10 0x1066579a4 0x106658108 0x106697328 0x1065f7d14 0x1065f81ec 0x1065fd0b4 0x106696384 0x106697af8 0x106688b58 0x102e9e5a0 0x102e9e610 0x102e9e664 0x18671b338 0x102e9dffc 0x102fd8d40 0x102e064ec 0x106682b0c 0x106682e24 0x1065f1110 0x106688720 0x106688998 0x1066c4c10 0x1066552b8 0x106655aa4 0x1066c4c10 0x10663f77c 0x10663f404 0x10663f808 0x106652334 0x10663accc 0x105ae23b4 0x105ae5580 0x105afbdc4 0x105af26f4 0x181c5dcd4 0x181c17eac 0x181c2b3b8 0x19d5bb38c 0x1845cb6a8 0x18434a7f4 0x199344184 0x10318f4a0 0x10318f428 0x103190e70 0x1043e1a24)
libc++abi: terminating with uncaught exception of type NSException
dyld4 config: DYLD_LIBRARY_PATH=/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString substringWithRange:]: Range {12, 2} out of bounds; string length 12'
terminating with uncaught exception of type NSException

**Comment by xiaoxuan-Tuya** [comment]
Hi , finofantashi 
Thanks for your feedback . For your issue  , it seems caused by a local exception .  You could post the relevant code so that we can find out the cause .

**Comment by ffantasy94** [comment]
Hi, @xiaoxuan-Tuya 
Please check: https://gyazo.com/bce0669e6117ef159a28720303b06ceb

**Comment by xiaoxuan-Tuya** [comment]
Hi , @finofantashi

I had checked it and the issue was caused by the invalid dp data in your `TuyaSmartLightDevice ` .  It seems that the length of `colourHSV ` is less than 15. You could check it or refer the [sample](https://github.com/tuya/tuya-lighting-ios-sdk/blob/main/TuyaSmartDemo/Classes/DeviceList/Controller/TYDemoDJPanelViewController.m).
