### ISSUE TITLE
dps data type error

### ISSUE THREAD

**Issue by ffantasy94** [tuya/tuya-lighting-ios-sdk#2]
```
 tuyaLight?.turnLight(on: false, success: {
                    }, failure: { error in
                        observer(.error(error!))
                    })
```

Printing description of error:
▿ Optional<Error>
  - some : Error Domain=com.tuya.smart.devicecorekit Code=3005 "dps data type error" UserInfo={NSLocalizedDescription=dps data type error}

**Comment by xiaoxuan-Tuya** [comment]
Hi , @finofantashi 

From the error description we  could see that the type of DP in your `TuyaSmartLightDevice ` is invalid .  You could refer the sample or  see the [doc](https://developer.tuya.com/en/docs/app-development/function-description?id=Kaik7pg0vpn2p#title-5-Get%20light%20type) .
